# Generated by Django 6.0.3 on 2026-03-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='익명', max_length=50),
        ),
    ]
